### ISSUE TITLE
Hardware?

### ISSUE THREAD

**Issue by thucar** [netjordan/node-red-contrib-ola#5]
I'm looking to add DMX lighting to my NodeRED setup and this plugin came up in my searches. Now I understand this plugin uses OLE. Does that mean that it only runs on the Number1 hardware? Which seems to be hard to obtain these days...

**Comment by thucar** [comment]
Nevermind... just found the OLE hw list :)

**Comment by peternewman** [comment]
Just to try and clarify for anyone else who finds this, this plugin uses OLA the Open Lighting Architecture, that supports a whole range of dongles, network protocols and direct outputs listed on our homepage:
https://www.openlighting.org/ola/

One of those supported dongles is Open Lighting Embedded ( https://www.openlighting.org/ole/ ), a set of building blocks to make your own DMX related hardware, an example of which is the Number1.

You can also use OLA to drive an Enttec OpenDMX or DMX USB Pro, the UART on a Pi or any number of other options too.
